# Change baseurl before deploy
baseurl = "https://blog.ouraihub.com"
languageCode = "zh-cn"
title = "Product Hunt 每日中文热榜"
defaultContentLanguage = "zh-cn"
hasCJKLanguage = true

# Disqus、分页等可选参数
disqusShortname = ""
[pagination]
pagerSize = 10