name: Deploy to AIBriefs.github.io

on:
    push:
        branches: [main, master]  # 支持 main 和 master 分支
    workflow_dispatch:  # 允许手动触发

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        permissions:
            contents: read

        steps:
            - name: Checkout source repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  submodules: true  # 获取 Hugo 主题

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version: "^1.21.0"

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v3
              with:
                  hugo-version: "latest"
                  extended: true

            - name: Cache Hugo resources
              uses: actions/cache@v4
              with:
                  path: resources
                  key: ${{ runner.os }}-hugo-resources-${{ hashFiles('**/go.sum') }}
                  restore-keys: |
                      ${{ runner.os }}-hugo-resources-

            - name: Build with Hugo
              env:
                  HUGO_ENVIRONMENT: production
                  HUGO_ENV: production
              run: |
                  hugo \
                      --gc \
                      --minify \
                      --baseURL "https://AIBriefs.github.io/"

            - name: Deploy to AIBriefs.github.io
              uses: peaceiris/actions-gh-pages@v3
              with:
                  # 使用 Personal Access Token 部署到外部仓库
                  personal_token: ${{ secrets.DEPLOY_TOKEN }}
                  external_repository: AIBriefs/AIBriefs.github.io
                  publish_branch: main  # 或者 master，取决于目标仓库的默认分支
                  publish_dir: ./public
                  force_orphan: true  # 创建独立的 gh-pages 分支
                  user_name: 'github-actions[bot]'
                  user_email: 'github-actions[bot]@users.noreply.github.com'
                  commit_message: 'Deploy from ${{ github.repository }}@${{ github.sha }}'
